PPROTEIN_GIT_REPOSITORY=/home/isucon/repo

ISUCON_DB_HOST=isuports-3.t.isucon.dev
ISUCON_DB_PORT=3306
ISUCON_DB_USER=narusejun
ISUCON_DB_PASSWORD=narusejun
ISUCON_DB_NAME=isuports

ISUCON_SNOWFLAKE_NODE_ID=1